---
name: Service
description: 'The Service class describes a network service.  The service is described
  by a protocol, port, protocol header field, and application providing or using the
  service. '
aggregates:
  ServiceName:
    name: ServiceName
    multiplicity: 0..1
    type: 
    description: A protocol name.
  Port:
    name: Port
    multiplicity: 0..1
    type: INTEGER
    description: A port number.
  Portlist:
    name: Portlist
    multiplicity: 0..1
    type: PORTLIST
    description: A list of port numbers.
  ProtoCode:
    name: ProtoCode
    multiplicity: 0..1
    type: INTEGER
    description: A transport-layer (Layer 4) protocol- specific code field (e.g.,
      ICMP code field).
  ProtoType:
    name: ProtoType
    multiplicity: 0..1
    type: INTEGER
    description: A transport-layer (Layer 4) protocol- specific type field (e.g.,
      ICMP type field).
  ProtoField:
    name: ProtoField
    multiplicity: 0..1
    type: INTEGER
    description: A transport-layer (Layer 4) protocol- specific flag field (e.g.,
      TCP flag field).
  ApplicationHeader:
    name: ApplicationHeader
    multiplicity: 0..1
    type: 
    description: A protocol header.  See Section 3.20.2.
  EmailData:
    name: EmailData
    multiplicity: 0..1
    type: 
    description: Headers associated with an email message.  See Section 3.21.
  Application:
    name: Application
    multiplicity: 0..1
    type: SOFTWARE
    description: The application acting as either the client or the server for the
      service.
  ip-protocol:
    name: ip-protocol
    multiplicity: 0..1
    type: INTEGER
    description: The IANA-assigned IP protocol number per [IANA.Protocols].  The attribute
      MUST be set if a Port, Portlist, ProtoCode, ProtoType, or ProtoField class is
      present.
  observable-id:
    name: observable-id
    multiplicity: 0..1
    type: ID
    description: See Section 3.3.2.
attributes: {}
